# project settings
find_features = false  # required
train_model =  false # required
apply_model = true # required
seed = 42 # optional, default is "random"

input_files = "individual"  # required if find_features or train_model are true; options: "reference", "individual"; default is "reference"



# files
output_dir = "cwd"  # Optional, default is "cwd"

reference_quant_file = ""  # required if find_features or train_model are true and input_files = "reference"
reference_meta_file = ""  # required if find_features or train_model are true and input_files = "reference"

feature_quant_file = ""  # required if find_features = true and input_files = "individual"
feature_meta_file = ""  # required if find_features = true and input_files = "individual"
feature_file = "RegressionTests/ApplyClassifierOnlyTest/input_features.tsv"  # required if find_features = false

train_quant_file = ""  # required if train_model = true and input_files = "individual"
train_meta_file = ""  # required if train_model = true and input_files = "individual"
validate_quant_file = ""  # required if train_model = true and input_files = "individual"
validate_meta_file = ""  # required if train_model = true and input_files = "individual"
model_file = "RegressionTests/ApplyClassifierOnlyTest/input_trained_model_and_model_metadata.pkl"  # required if train_model = false and apply_model = true

experimental_quant_file = "RegressionTests/test_data/Experimental_quant.tsv"  # required if apply_model = true



# find feature settings
k_rules = 15  # optional, default is 15, max is 50
missingness_cutoff = 0.5  # optional, default is 0.5
disjoint = false  # optional, default is false
mutual_information = true  # optional, default is true
mutual_information_cutoff = 0.7  # optional, default is 0.7



# train model settings
impute_NA_missing = true  # optional, default is true
cross_val = 5
model_type = "RF"  # optional, default is "RF"
autotune_hyperparameters = ""  # if blank, no autotune will be done. User inputs either "random" or "grid"
autotune_n_iter = 20  # optional, default is 20 for random search
verbose = 0  # optional, default is 0, allowed values include [0, 1, 2, 3, 4]


# apply model settings
prediction_format = "classes"  # can be 'classes' or 'probabilities', default is 'classes'
